blooger/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root :to => 'posts#index'

  resources :posts do
    resources :comments, :except => [:index]
  end
end

blooger/app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :text, :presence => true
  belongs_to :post
end

blooger/app/models/post.rb
class Post < ActiveRecord::Base
 validates :title, :presence => true
 validates :content, :presence => true
 has_many :comments
end

blooger/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

blooger/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

blooger/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def new
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comments_params)
    if @comment.save
      flash[:notice] = "Comment added"
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    if @comment.update(comments_params)
      flash[:notice] = "Comment updated"
      redirect_to posts_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "Comment deleted"
    redirect_to posts_path(@comment.post)
  end

private
  def comments_params
    params.require(:comment).permit(:text)
  end
end

blooger/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(posts_params)
    if @post.save
      flash[:notice] = "Blog post successfully saved"
      redirect_to posts_path
    else
      flash[:alert] = "There was a problem saving your post"
      render :new
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(posts_params)
      flash[:notice] = 'Your post has been updated'
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Post deleted"
    redirect_to posts_path
  end


private
  def posts_params
    params.require(:post).permit(:title, :content)
  end

end

blooger/app/helpers/application_helper.rb
module ApplicationHelper
end

blooger/app/views/comments/_form.html.erb
<%= form_for [@post, @comment], class:"form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :text, class:"form-label" %></div>
    <%= f.text_area :text, class:"form-control" %>
  <br>
    <%= f.submit "Submit", class: ['btn-info', 'btn']%>
  </div>
<% end %>

blooger/app/views/comments/edit.html.erb
<h3>Edit Comment</h3>

<%= render 'form' %>

blooger/app/views/comments/new.html.erb
<h3>New Comment</h3>

<%= render 'form' %>

blooger/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blooger</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <a class="navbar-brand" href="/">Blooger</a>
        <div class="nav navbar-nav navbar-right">
          <%= link_to "Add Post", new_post_path, class: ['btn-primary', 'btn']%>
        </div>
      </div>
    </nav>

    <div id="user_nav">
      <% if user_signed_in? %>
        Logged-in as <strong><%= current_user.email %></strong>.
        <%= link_to 'Edit Profile', edit_user_registration_path %> |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Signup', new_user_registration_path %> |
        <%= link_to 'Login', new_user_session_path %>
      <% end %>
    </div>

    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <%= yield %>
  </div>
</body>
</html>

blooger/app/views/posts/_form.html.erb
<%= form_for @post, class:"form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :title, class:"form-label" %></div>
    <%= f.text_field :title, class:"form-control" %>
    <%= f.label :content, class:"form-label" %>
    <%= f.text_area :content, class:"form-control" %>
  <br>
    <%= f.submit "Post", class: ['btn-info', 'btn']%>
  </div>
<% end %>

blooger/app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= render 'form' %>

blooger/app/views/posts/index.html.erb
<h2>Recent Posts</h2>
<br >

<br >
<% @posts.each do |post| %>
  <div class="well"><p><%= link_to post.title, post_path(post) %></p></div>
<% end %>

blooger/app/views/posts/new.html.erb
<%= render 'form' %>

blooger/app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<h5>Post created: <%= @post.created_at.to_date %></h5>
<br >

<p><%= @post.content %></p>
<br >
<p>
  <%= link_to "Comment", new_post_comment_path(@post), class: ['btn-success', 'btn-sm'] %>
  <!--  add that current user must be equal to user that created post/comments in order to edit them-->
  <% if current_user %>
    <%= link_to "Edit Post", edit_post_path(@post), class: ['btn-warning', 'btn-sm'] %>
    <%= link_to "Delete Post", post_path(@post), class: ['btn-danger', 'btn-sm'], :data => { :confirm => "Are you sure?",
                                                            :method => "delete" } %>
  <% end %>
</p>
<br >
<br >
<p>
  <% if @post.comments.any? %>
    <h4>Comments</h4>
    <% @post.comments.each do |comment| %>
      <div class="well"><p>
        <%= comment.text %><br><br>
        <% if current_user %>
          <%= link_to 'Edit Comment', edit_post_comment_path(@post, comment), class: ['btn-warning', 'btn-sm'] %>
          <%= link_to 'Delete Comment', post_comment_path(@post, comment), class: ['btn-danger', 'btn-sm'], :data => { :confirm => "Are you sure?",
                                                                                                           :method => "delete" } %>

        <% end %>
    </p></div>
    <% end %>
  <% else %>
    <p>There are no comments yet for this post.</p>
  <% end %>
</p>

<p><%= link_to "Home", posts_path %></p>