stackIT-master/config/routes.rb
Rails.application.routes.draw do
  get '/' => 'home#index'
  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users do
    resources :questions
  end

  resources :questions do
      resources :responses
  end
end

stackIT-master/app/models/question.rb
class Question < ActiveRecord::Base
  validates :ask, :presence => true
  has_many :responses
  belongs_to :user

  def bestFirst
    self.responses.sort_by {|obj| obj.best ? 0 : 1}    
  end
end

stackIT-master/app/models/response.rb
class Response < ActiveRecord::Base
  validates :answer, :presence => true
  belongs_to :question
  belongs_to :user
  after_create :send_notification

  def send_notification
    UserMailer.response_notification(self.question.user).deliver_now
  end

end

stackIT-master/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password
  has_many :questions
  has_many :responses

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
end

stackIT-master/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


end

stackIT-master/app/controllers/home_controller.rb
class HomeController <ApplicationController
  def index

  end
  
end

stackIT-master/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
    @question = Question.new
    @user = current_user
  end

  def show
    @question = Question.find(params[:id])
    @response = Response.new

  end

  def new
    @question = Question.new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = "Question Successfully Asked!"
    else
      flash[:alert] = "There was a problem submitting your question"
    end
    redirect_to :back
  end

  private
  def question_params
    params.require(:question).permit(:ask)
  end

end

stackIT-master/app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def create
    question = Question.find(params[:question_id])
    response = question.responses.new(response_params)
    response.user_id = current_user.id
    if response.save
      flash[:notice] = "Answer Successfully Added!"
    else
      flash[:alert] = "There was a problem submitting your answer"
    end
    redirect_to :back
  end

  def update
    response = Response.find(params[:id])
    response.update(response_params)
    response.save()
    binding.pry
    redirect_to user_path(current_user)
  end

  private
  def response_params
    params.require(:response).permit(:answer, :best)
  end

end

stackIT-master/app/controllers/sessions_controller.rb
class SessionsController <ApplicationController
  def new

  end

  def create
  #try to authenticate the user - if they authenticate successfully, an instance of the User model is returned
    @user = User.authenticate(params[:email], params[:password])
  #if an instance is returned and @user is not nil...
    if @user
    #let the user know they've been logged in with a flash message
      flash[:notice] = "You've been logged in."
    #THIS IS THE MOST IMPORTANT PART. Actually log the user in by storing their ID in the session hash with the [:user_id] key!
      session[:user_id] = @user.id
    #then redirect them to the homepage
      redirect_to questions_path
    else
    #whoops, either the user wasn't in the database or their password is incorrect, so let them know, then redirect them back to the log in page
      flash[:alert] = "There was a problem logging you in."
      redirect_to log_in_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

stackIT-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new

  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to StackIT!"
      redirect_to questions_path
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

stackIT-master/app/helpers/application_helper.rb
module ApplicationHelper
end

stackIT-master/app/views/questions/_form.html.erb
<%= form_for @question, class:"form-horizontal" do |f| %>
  <%= f.label :ask, class:"form-label" %>
  <%= f.text_field :ask, class:"form-control" %>
  <br>
  <%= f.submit "Submit", class: ['btn-info', 'btn'] %>
<% end %>

stackIT-master/app/views/questions/index.html.erb
<h1>StackIT</h1>

<h4>Welcome <%= @user.email %></h4>


<%= render 'form' %>

<br>
<br>

<h2>Recent Questions</h2>
  <% @questions.each do |question| %>
<div id="questions">
    <h3><%= link_to question.ask, question_path(question) %></h3>
</div>
  <% end %>

stackIT-master/app/views/questions/show.html.erb
<h1><%= @question.ask %></h1>

<br>
<h3>Answers</h3>
  <% @question.bestFirst.each do |response| %>
    <div class="well">
      <p><b>User <%= response.user.email %> says:</b></p>
      <p><%= response.answer %></p>
    </div>
  <% end %>


<%= form_for [@question, @response], class:"form-horizontal" do |f| %>
  <%= f.label :answer, class:"form-label" %>
  <%= f.text_field :answer, class:"form-control" %>
<br>
  <%= f.submit "AnswerIT", class: ['btn-warning', 'btn'] %>
<% end %>

stackIT-master/app/views/users/new.html.erb
<h2>Sign In</h2>

<%= form_for User.new do |f| %>
<%= f.label :email %>
<%= f.text_field :email %>
<%= f.label :password %>
<%= f.password_field :password %>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>
<%= f.submit "Sign Up" %>
<% end %>

stackIT-master/app/views/users/show.html.erb
<h4>Your Questions</h4>
<% @user.questions.each do |q|%>
  <ul>
    <li><%= q.ask %></li>
      <% q.bestFirst.each do |r| %>
        <ul>
          <div id="response-id-#{r.id}">
            <li><%= r.answer %> | <%= link_to 'Best Answer', question_response_path(q, r, response: {best: true}), data: {method: "patch"}  %></li>
            </div>
        </ul>
      <% end %>
  </ul>
<% end %>


<h4>Your Reponses</h4>
<% @user.responses.each do |r|%>
  <ul>
    <li>Question: <%= r.question.ask %></li>
    <p>Response: <%= r.answer %><p>
  </ul>
<% end %>